project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tasks/", include('tasks.urls')),
    path("quality_control/", include('quality_control.urls'))
]

quality_control/urls.py
from django.urls import path, include
from quality_control import views
from tasks.views import TaskDetailView, ProjectDetailView

app_name = 'quality_control'

urlpatterns = [
    path('', views.index, name='index'),
    path('project/<int:project_id>/bugs/<int:bug_id>/update', views.BugUpdateView.as_view(), name='update_bug'),
    path('project/<int:project_id>/bugs/<int:bug_id>/update', views.update_bug, name='update_bug'),
    path('project/<int:project_id>/features/<int:feature_id>/update', views.FeatureUpdateView.as_view(), name='update_feature'),
    path('project/<int:project_id>/features/<int:feature_id>/update', views.update_feature, name='update_feature'),
    path('bugs/<int:bug_id>/delete/', views.BugDeleteView.as_view(), name='delete_bug_report'),
    path('bugs/<int:bug_id>/delete/', views.delete_bug_report, name='delete_bug_report'),
    path('features/<int:feature_id>/delete/', views.FeatureDeleteView.as_view(), name='delete_feature_request'),
    path('features/<int:feature_id>/delete/', views.delete_feature_request, name='delete_feature_request'),
    path('project/<int:project_id>/bugs/new/', views.create_bug_report, name='create_bug_report'),
    path('project/<int:project_id>/features/new/', views.create_feature_request, name='create_feature_request'),
    path('bugs/', include([
        path('', views.bug_list, name='bug_list'),
        path('<int:bug_id>/', views.BugReportDetailView.as_view(), name='bug_detail'),
        path('<int:bug_id>/tasks/<int:task_id>/', TaskDetailView.as_view(), name='task_detail'),
        path('<int:bug_id>/projects/<int:project_id>/', ProjectDetailView.as_view(), name='project_detail'),
    ])),
    path('features/', include([
        path('', views.feature_list, name='feature_list'),
        path('<int:feature_id>/', views.FeatureRequestDetailView.as_view(), name='feature_id_detail'),
        path('<int:feature_id>/tasks/<int:task_id>/', TaskDetailView.as_view(), name='task_detail'),
        path('<int:feature_id>/projects/<int:project_id>/', ProjectDetailView.as_view(), name='project_detail'),
    ]))
]

tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('feedback/', views.feedback_view, name='feedback'),
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),

]

quality_control/models.py
from django.db import models
from tasks.models import Project, Task


class BugReport(models.Model):
    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена')
    ]
    PRIORITY_CHOICES = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        related_name='bug_reports',
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        related_name='bug_reports',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New',
    )
    priority = models.CharField(
        max_length=1,
        choices=PRIORITY_CHOICES,
        default='1',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeatureRequest(models.Model):
    STATUS_CHOICES = [
        ('Review', 'Рассмотрение'),
        ('Accepted', 'Принято'),
        ('Declined', 'Отклонено')
    ]
    PRIORITY_CHOICES = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        related_name='feature_requests',
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        related_name='feature_requests',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New',
    )
    priority = models.CharField(
        max_length=1,
        choices=PRIORITY_CHOICES,
        default='1',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

quality_control/forms.py
from django.forms import ModelForm
from .models import BugReport, FeatureRequest
from tasks.models import Task


class BugReportForm(ModelForm):

    def __init__(self, *args, **kwargs):
        project_id = kwargs.pop('initial', {}).get('project_id')
        super().__init__(*args, **kwargs)
        print(project_id)
        if project_id:
            self.fields['task'].queryset = Task.objects.filter(project_id=project_id)

    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'task']


class FeatureRequestForm(ModelForm):

    def __init__(self, *args, **kwargs):
        project_id = kwargs.pop('initial', {}).get('project_id')
        super().__init__(*args, **kwargs)
        print(project_id)
        if project_id:
            self.fields['task'].queryset = Task.objects.filter(project_id=project_id)

    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'task']

quality_control/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy

from django.views import View
from django.views.generic import DetailView, ListView, DeleteView, UpdateView, CreateView

from .models import BugReport, FeatureRequest
from tasks.models import Project

from .forms import BugReportForm, FeatureRequestForm


def index(request):
    return render(request, 'quality_control/index.html')


class IndexView(View):
	def get(self, request, *args, **kwargs):
		return render(request, 'quality_control/index.html')


def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bugs_list.html', {'bugs_list': bugs})


class BugReportListView(ListView):
    model = BugReport
    template_name = 'quality_control/bugs_list.html'


def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/features_list.html', {'features_list': features})


class FeatureRequestListView(ListView):
    model = FeatureRequest
    template_name = 'quality_control/features_list.html'


def create_bug_report(request, project_id):
    project = get_object_or_404(Project, pk=project_id)

    if request.method == 'POST':
        form = BugReportForm(request.POST or None, initial={'project_id': None})
        if form.is_valid():
            bug = form.save(commit=False)
            bug.project = project
            bug.save()
            return redirect('quality_control:bug_list')
    else:
        form = BugReportForm(initial={'project_id': project.id})

    return render(request, 'quality_control/bug_report_form.html', {'form': form, 'project': project})


def create_feature_request(request, project_id):
    project = get_object_or_404(Project, pk=project_id)

    if request.method == 'POST':
        form = FeatureRequestForm(request.POST or None, initial={'project_id': None})
        if form.is_valid():
            feature = form.save(commit=False)
            feature.project = project
            feature.save()
            return redirect('quality_control:feature_list')
    else:
        form = FeatureRequestForm(initial={'project_id': project.id})

    return render(request, 'quality_control/feature_request_form.html', {'form': form, 'project': project})


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')


class BugReportDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_report_detail.html'
    context_object_name = 'bug'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        bug = self.object
        task = bug.task
        project = bug.project
        return render(request, 'quality_control/bug_report_detail.html', {'bug': bug, 'task': task, 'project': project})


def bug_detail(request, bug_id):
	bug = get_object_or_404(BugReport, id=bug_id)
	task = bug.task
	project = bug.project

	return render(request, 'quality_control/bug_detail.html', {'bug': bug, 'task': task, 'project': project})


class FeatureRequestDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        feature = self.object
        task = feature.task
        project = feature.project
        return render(request, 'quality_control/feature_detail.html', {'feature': feature, 'task': task, 'project': project})


def feature_detail(request, feature_id):
	feature = get_object_or_404(FeatureRequest, id=feature_id)
	task = feature.task
	project = feature.project

	return render(request, 'quality_control/feature_detail.html', {'feature': feature, 'task': task, 'project': project})


class BugReportCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_form.html'


    def form_valid(self, form):
        project_id = self.kwargs['project_id']
        project = Project.objects.get(pk=project_id)
        form.instance.project = project

        return super().form_valid(form)


    def get_success_url(self):
        return reverse('quality_control:bug_list')


class FeatureRequestCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_form.html'

    def form_valid(self, form):
        project_id = self.kwargs['project_id']
        project = Project.objects.get(pk=project_id)
        form.instance.project = project
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('quality_control:feature_list')


def update_bug(request, project_id, bug_id):
    project = get_object_or_404(Project, pk=project_id)
    bug = get_object_or_404(BugReport, pk=bug_id)

    if request.method == 'POST':
        form = BugReportForm(request.POST or None, initial={'project_id': None}, instance=bug)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_detail', bug_id=bug.id)
    else:
        form = BugReportForm(initial={'project_id': project.id}, instance=bug)

    return render(request, 'quality_control/bug_update.html', {'form': form, 'bug': bug})


class BugUpdateView(UpdateView):
	model = BugReport
	form_class = BugReportForm
	template_name = 'quality_control/bug_update.html'
	pk_url_kwarg = 'bug_id'

	def get_success_url(self):
		return reverse_lazy('quality_control:bug_detail', kwargs={'bug_id': self.object.id})


def update_feature(request, project_id, feature_id):
    project = get_object_or_404(Project, pk=project_id)
    feature = get_object_or_404(FeatureRequest, pk=feature_id)

    if request.method == 'POST':
        form = FeatureRequestForm(request.POST or None, initial={'project_id': None}, instance=feature)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_id_detail', feature_id=feature.id)
    else:
        form = FeatureRequestForm(initial={'project_id': project.id}, instance=feature)

    return render(request, 'quality_control/feature_update.html', {'form': form, 'feature': feature})


class FeatureUpdateView(UpdateView):
	model = FeatureRequest
	form_class = FeatureRequestForm
	template_name = 'quality_control/feature_update.html'
	pk_url_kwarg = 'feature_id'

	def get_success_url(self):
		return reverse_lazy('quality_control:feature_id_detail', kwargs={'feature_id': self.object.id})


def delete_bug_report(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    bug.delete()

    return redirect('quality_control:bug_list')


class BugDeleteView(DeleteView):
	model = BugReport
	pk_url_kwarg = 'bug_id'
	success_url = reverse_lazy('quality_control:bug_list')
	template_name = 'quality_control/bug_confirm_delete.html'


	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['bug'] = self.object

		return context


def delete_feature_request(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    feature.delete()

    return redirect('quality_control:feature_list')

class FeatureDeleteView(DeleteView):
	model = FeatureRequest
	pk_url_kwarg = 'feature_id'
	success_url = reverse_lazy('quality_control:feature_list')
	template_name = 'quality_control/feature_confirm_delete.html'


	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['feature'] = self.object

		return context

quality_control/templates/quality_control/bug_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление отчёта бага</h1>
    <p>Вы уверены, что хотите удалить отчёт "{{ bug.title }}"?</p>

    <form action="{% url 'quality_control:delete_bug_report' bug.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_detail' bug.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_report_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Баг {{ bug.title }}</h1>
    <p>Описание: {{ bug.description }}</p>
    <h1>Проект <a href="{% url 'tasks:project_detail' project.id %}">{{ bug.project }}</a> </h1>
    <h1>Задача <a href="{% url 'tasks:task_detail' project.id task.id %}">{{ bug.task }}</a> </h1>

    <p><a href="{% url 'quality_control:update_bug' project.id bug.id %}">Изменить отчёт бага</a></p>
    <p><a href="{% url 'quality_control:delete_bug_report' bug.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот отчёт?');">Удалить отчёт бага</a></p>


{% endblock %}

quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Добавить отчёт о баге в задачу {{ task.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать отчёт о баге</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение отчёта бага: {{ bug.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/bugs_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список багов</h1>
    <ul>
        {% for bug in bugs_list %}
            <li><a href="{% url 'quality_control:bug_detail' bug.id %}">{{ bug.title }} - {{ bug.project }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/feature_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса улучшения</h1>
    <p>Вы уверены, что хотите удалить запрос "{{ feature.title }}"?</p>

    <form action="{% url 'quality_control:delete_feature_request' feature.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_id_detail' feature.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Запрос на улучшение {{ feature.title }}</h1>
    <p>Описание: {{ feature.description }}</p>
    <h1>Проект <a href="{% url 'tasks:project_detail' project.id %}">{{ feature.project }}</a> </h1>
    <h1>Задача <a href="{% url 'tasks:task_detail' task.id project.id %}">{{ feature.task }}</a> </h1>

    <p><a href="{% url 'quality_control:update_feature' project.id feature.id %}">Изменить запрос улучшения</a></p>
    <p><a href="{% url 'quality_control:delete_feature_request' feature.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот запрос?');">Удалить запрос улучшения</a></p>

{% endblock %}

quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Проект <a href="{% url 'tasks:project_detail' project.id %}">{{ project.name }}</a></h1>

<h2>Создать запрос на улучшение</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение запрос улучшения: {{ feature.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/features_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список запросов на улучшение</h1>
    <ul>
        {% for feature in features_list %}
            <li><a href="{% url 'quality_control:feature_id_detail' feature.id %}">{{ feature.title }} - {{ feature.project }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
        <h1>Страница приложения quality_control</h1>
        <a href="{% url 'quality_control:bug_list' %}">Список багов</a>
        <br>
        <a href="{% url 'quality_control:feature_list' %}">Список улучшений</a>
{% endblock %}